(assign a '(1 2 3 4 5 6))

(printhex (nth a 0))
(printchar 10)
(printhex (nth a 1))
(printchar 10)
(printhex (nth a 2))
(printchar 10)
(printhex (nth a 3))
(printchar 10)
(printhex (nth a 4))
(printchar 10)
(printhex (nth a 5))
(printchar 10)
(printhex (nth a 6))
(printchar 10)

