name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install iverilog
      run: sudo apt-get install -y iverilog
    - name: Where am I
      run: pwd && ls -l
    - name: Run Tests
      run: make test